name       : mpc
version    : 1.1.0
release    : 5
source     :
    - https://ftp.gnu.org/gnu/mpc/mpc-1.1.0.tar.gz : 6985c538143c1208dcb1ac42cedad6ff52e267b47e5f970183a3e75125b43c2e
homepage   : http://www.multiprecision.org/mpc/
license    : LGPL-3.0
devel      : true
summary    : The MPC package contains a library for the arithmetic of complex numbers with arbitrarily high precision and correct rounding of the result.
description: |
    The MPC package contains a library for the arithmetic of complex numbers with arbitrarily high precision and correct rounding of the result.
emul32     : yes
builddeps  :
    - gmp-32bit-devel
    - mpfr-32bit-devel
component  : system.base
patterns   :
    - devel :
        - /usr/share/info
        - /usr/share/doc
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
