name        : mpc
version     : 1.0.1
release     : 3
source      :
    - http://ftp.gnu.org/gnu/mpc/mpc-1.0.1.tar.gz : ed5a815cfea525dc778df0cb37468b9c1b554aaf30d9328b1431ca705b7400ff
homepage    : http://multiprecision.org/
devel       : true
license     :
    - GPL-3.0
summary     : The MPC package contains a library for the arithmetic of complex numbers with arbitrarily high precision and correct rounding of the result. 
description : |
    The MPC package contains a library for the arithmetic of complex numbers with arbitrarily high precision and correct rounding of the result.
emul32     : yes
patterns   :
    - devel: [/usr/share/info, /usr/share/doc]
setup      : |
    %configure --prefix=/usr --disable-static
build      : |
    %make
install    : |
    %make_install
    %make clean
