name       : mpc
version    : 1.0.3
release    : 4
source     :
    - https://ftp.gnu.org/gnu/mpc/mpc-1.0.3.tar.gz : 617decc6ea09889fb08ede330917a00b16809b8db88c29c31bfbb49cbf88ecc3
homepage   : http://multiprecision.org/
devel      : true
license    :
    - GPL-3.0
summary    : The MPC package contains a library for the arithmetic of complex numbers with arbitrarily high precision and correct rounding of the result.
description: |
    The MPC package contains a library for the arithmetic of complex numbers with arbitrarily high precision and correct rounding of the result.
emul32     : yes
builddeps  :
    - gmp-32bit-devel
    - mpfr-32bit-devel
component  : system.base
patterns   :
    - devel:
        - /usr/share/info
        - /usr/share/doc
setup      : |
    %configure --prefix=/usr --disable-static
build      : |
    %make
install    : |
    %make_install
